### ISSUE TITLE
Please fix bugtracker link

### ISSUE THREAD

**Issue by pcav** [Kanahiro/EZPrinter#1]
it currently points to your personal GH page.
Arigatou.

**Comment by Kanahiro** [comment]
I fixed. Thank you.

**Comment by pcav** [comment]
Almost ;)
It should be:
https://github.com/Kanahiro/EZPrinter/issues
Thanks.

**Comment by Kanahiro** [comment]
Oh sorry, I have re-fixed.

**Comment by pcav** [comment]
Thanks
