### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [Kanahiro/EZPrinter#2]
The functionality described in the About seems already present in other QGIS plugins.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by Kanahiro** [comment]
Thank you for your reviewing.
I re-wrote the plugin explanations and fixed a bugtracker url.
Please check it.

**Comment by pcav** [comment]
Thanks for this. I see at least one plugin doing apparently a very similar thing:
https://plugins.qgis.org/plugins/QuickPrint/
Please clarify the difference with yours.
Sorry for bothering, I hope you'll understand our point here.
Cheers.

**Comment by Kanahiro** [comment]
Thank you for your response.
As you say, QuickPrint can output PDF files as EZPrinter do, but there is a big difference between these about processes users take, I think.
I mean, only EZPrinter users can define Print Area by a Rectangle the plugin provide.
The users can understand the area to be printed at a glance.
I believe this concept is only in my plugin.
To tell this function correctly, I added following GIF animation image on Plugin description page.
![sample](https://user-images.githubusercontent.com/20744195/71010340-06d4a480-212f-11ea-94aa-2ce6ac0c3954.gif)

Regards.

**Comment by pcav** [comment]
Thanks Kanahiro-san for clarifying
