### ISSUE TITLE
プラグイン起動でイニシャライズ処理が何度もかかる

### ISSUE THREAD

**Issue by ozo360** [Kanahiro/EZPrinter#6]
v1.3で確認しています。

ツールバーからEZPrinterのアイコンをクリックすると毎回イニシャライズが発生するため
コンボ（用紙と縮尺）の項目がクリックした回数分増殖します。
画面のイニシャライズ（initCustomGUIs）は初回のみ実行するように制御が必要です。

明日（11/3）プルリクエストを投げられるかもしれません。

**Comment by ozo360** [comment]
プラグイン起動時にコンボをリフレッシュする必要があればremoveItemしてから追加が必要です。
（その場合でもコネクトは1回の方がいいです）

**Comment by Kanahiro** [comment]
closed by #7.
